### ISSUE TITLE
Unable to instantiate model: code=129, Model format not supported (no matching implementation found) (type=value_error)

### ISSUE THREAD

**Issue by Constey** [carru/workgpt#2]
thanks for that nice project, it's idea is awesome and what i was looking for.

i've run the code today and getting an issue with the model:
`gguf_init_from_file: invalid magic characters lmgg.
gguf_init_from_file: invalid magic characters lmgg.
gguf_init_from_file: invalid magic characters lmgg.
Traceback (most recent call last):
  File "C:\dev\workgpt\init.py", line 3, in <module>
    workgpt.init_chain()
  File "C:\dev\workgpt\workgpt.py", line 17, in init_chain
    llm = GPT4All(model=MODEL_PATH)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\langchain_core\load\serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model: code=129, Model format not supported (no matching implementation found) (type=value_error)`

I think the ggml-gpt4all-j-v1.3-groovy.bin does not work with the latest langchain version is that possible? currently loading, but i'll try another gpt4all model like em_german_mistral_v01.Q4_0.gguf next.

**Comment by Constey** [comment]
currently package versions:
`C:\dev\workgpt>pip list
Package                   Version
------------------------- ------------
aiohttp                   3.9.1
aiosignal                 1.3.1
altair                    5.2.0
antlr4-python3-runtime    4.9.3
anyio                     4.2.0
atlassian-python-api      3.41.4
attrs                     23.2.0
backoff                   2.2.1
beautifulsoup4            4.12.2
blinker                   1.7.0
cachetools                5.3.2
certifi                   2023.11.17
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
chromadb                  0.3.29
click                     8.1.7
clickhouse-connect        0.5.22
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.0
cryptography              41.0.7
cycler                    0.12.1
dataclasses-json          0.6.3
Deprecated                1.2.14
duckdb                    0.9.2
effdet                    0.4.1
emoji                     2.9.0
fastapi                   0.85.1
filelock                  3.13.1
filetype                  1.2.0
flatbuffers               23.5.26
fonttools                 4.47.0
frozenlist                1.4.1
fsspec                    2023.12.2
gitdb                     4.0.11
GitPython                 3.1.40
gpt4all                   2.0.2
greenlet                  3.0.3
h11                       0.14.0
hnswlib                   0.8.0
httptools                 0.6.1
huggingface-hub           0.20.1
humanfriendly             10.0
idna                      3.6
importlib-metadata        6.11.0
iopath                    0.1.10
Jinja2                    3.1.2
joblib                    1.3.2
jsonpatch                 1.33
jsonpath-python           1.0.6
jsonpointer               2.4
jsonschema                4.20.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
langchain                 0.0.354
langchain-community       0.0.8
langchain-core            0.1.5
langdetect                1.0.9
langsmith                 0.0.77
layoutparser              0.3.4
lxml                      5.0.0
lz4                       4.3.3
markdown-it-py            3.0.0
markdownify               0.11.6
MarkupSafe                2.1.3
marshmallow               3.20.1
matplotlib                3.8.2
mdurl                     0.1.2
monotonic                 1.6
mpmath                    1.3.0
multidict                 6.0.4
mypy-extensions           1.0.0
networkx                  3.2.1
nltk                      3.8.1
numpy                     1.26.3
oauthlib                  3.2.2
omegaconf                 2.3.0
onnx                      1.15.0
onnxruntime               1.15.1
opencv-python             4.9.0.80
overrides                 7.4.0
packaging                 23.2
pandas                    2.1.4
pdf2image                 1.16.3
pdfminer.six              20221105
pdfplumber                0.10.3
pikepdf                   8.11.2
pillow                    10.2.0
pip                       23.2.1
poppler-utils             0.1.0
portalocker               2.8.2
posthog                   3.1.0
protobuf                  4.25.1
pulsar-client             3.4.0
pyarrow                   14.0.2
pycocotools               2.0.7
pycparser                 2.21
pydantic                  1.10.13
pydeck                    0.8.1b0
Pygments                  2.17.2
pyparsing                 3.1.1
pypdf                     3.17.4
pypdfium2                 4.25.0
pyreadline3               3.4.1
pytesseract               0.3.10
python-dateutil           2.8.2
python-dotenv             1.0.0
python-iso639             2024.1.2
python-magic              0.4.27
python-multipart          0.0.6
pytz                      2023.3.post1
pywin32                   306
PyYAML                    6.0.1
rapidfuzz                 3.6.1
referencing               0.32.0
regex                     2023.12.25
requests                  2.31.0
requests-oauthlib         1.3.1
rich                      13.7.0
rpds-py                   0.16.2
safetensors               0.4.1
scikit-learn              1.3.2
scipy                     1.11.4
sentence-transformers     2.2.2
sentencepiece             0.1.99
setuptools                65.5.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
soupsieve                 2.5
SQLAlchemy                2.0.25
starlette                 0.20.4
streamlit                 1.29.0
sympy                     1.12
tabulate                  0.9.0
tenacity                  8.2.3
threadpoolctl             3.2.0
timm                      0.9.12
tokenizers                0.15.0
toml                      0.10.2
toolz                     0.12.0
torch                     2.1.2
torchvision               0.16.2
tornado                   6.4
tqdm                      4.66.1
transformers              4.36.2
typing_extensions         4.9.0
typing-inspect            0.9.0
tzdata                    2023.4
tzlocal                   5.2
unstructured              0.11.8
unstructured-client       0.15.1
unstructured-inference    0.7.18
unstructured.pytesseract  0.3.12
urllib3                   2.1.0
uvicorn                   0.25.0
validators                0.22.0
watchdog                  3.0.0
watchfiles                0.21.0
websockets                12.0
wrapt                     1.16.0
yarl                      1.9.4
zipp                      3.17.0
zstandard                 0.22.0
`
